project:
  type: website
  output-dir: docs

website:
  title: "Rasmus Gustafsson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: darkly
    mainfont: Georgia, serif;
    css: styles.css
    toc: true

editor: visual

